### ISSUE TITLE
Cache current round details to reduce the load on our DB server

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/spark-api#140]
Once we define the tasks for the current round, this value never changes.

Few ways to implement this improvement:

1. Cache the round details inside spark-api
2. Leverage Cloudflare CDN layer that's already in front of our API

**Comment by juliangruber** [comment]
Sounds good, either works for me. If we can do it in Cloudflare with low effort (syncing cache invalidation with rounds) I would prefer that, because it keeps our business logic clean.

**Comment by bajtos** [comment]
> > After merging, adjust https://dash.cloudflare.com/37573110e38849a343d93b727953188f/filspark.com/caching/cache-rules/7cc5c26ebc3c400c9666c5a0f83ac50d to read the `cache-control` header again
> 
> Done.


I also had to "Browser Cache TTL" setting on the page [Caching >> Configuration](https://dash.cloudflare.com/37573110e38849a343d93b727953188f/filspark.com/caching/configuration), otherwise "round not found" responses would be cached for 14400 seconds instead of the 60 seconds indicated by our server.

cc @juliangruber
