### ISSUE TITLE
Migrate to the new web3.storage API

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/spark-api#141]
See https://mailchi.mp/web3.storage/major-changes-to-web3storage?e=77416530cd

> what this means for you, a current web3.storage user. Here’s the tl;dr:
> - The new upload API and client is live. Its account system is completely separate from that of the legacy web3.storage.
> - The legacy web3.storage upload API, pinning service API, and w3name will sunset on January 9, 2024. Until then, you will still be able to upload to your legacy account up to your free account limit. The old dashboard can be found [here](https://old.web3.storage/account/).
> - All uploads to the legacy web3.storage prior to January 9, 2024 will continue to be stored until further notice, though over time latency and availability may degrade.

/cc @juliangruber FYI

**Comment by juliangruber** [comment]
blocked by https://github.com/web3-storage/w3up/issues/1175
