### ISSUE TITLE
We have run out of log storage allowance

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/spark-api#150]
https://papertrailapp.com/dashboard
> Your account has reached 96% log data transfer for this period.

The projected volume is 86.1GB/month. A plan with 7 days of searchable logs would cost us $425/monthly. That feels quite a lot to me.

Action items:

- [ ] Setup an alert so that we are notified about this problem in the future
- [x] Review our logs and look for options to reduce the load. For example, does spark-api need to log every incoming HTTP request?

Links:
- https://github.com/filecoin-station/spark-api/issues/108

**Comment by bajtos** [comment]
Maybe we can start by configuring our Fly log forwarder to ignore logs from spark-api - they are noise and very few of them are meaningful IMO.

See https://fly.io/docs/going-to-production/monitoring/exporting-logs/#shipping-specific-logs

**Comment by patrickwoodhead** [comment]
Can we close this issue @juliangruber ?

**Comment by juliangruber** [comment]
>  Setup an alert so that we are notified about this problem in the future

I believe this part is still missing.

<img width="603" alt="Screenshot 2024-01-03 at 13 32 41" src="https://github.com/filecoin-station/spark-api/assets/10247/b807d9b8-3a09-4c2f-b94e-92d510ed2112">

I think this is the closest we can get from PT. @bajtos are you ok enabling this option?

**Comment by bajtos** [comment]
I believe Additional Usage should be already enabled. If it's not then please do enable it.

**Comment by juliangruber** [comment]
You're right. Then this should be all we can do about this issues 🙏
