### ISSUE TITLE
Missing service name in Papertrail logs

### ISSUE THREAD

**Issue by bajtos** [filecoin-station/spark-api#394]
Papertrail logs don't show the service name like `spark-evaluate` anymore. This makes it difficult to search logs from spark-evaluate only. 

<img width="1047" alt="Screenshot 2024-08-09 at 09 52 06" src="https://github.com/user-attachments/assets/b827c80e-74ac-4b8a-96b7-db9a9d3e7a9d">

I believe we used to have the service name in the logs, do we need to tweak the configuration of the logshipper?

Loosely related:
- https://github.com/filecoin-station/spark-api/issues/108
- https://github.com/filecoin-station/spark-api/pull/281

**Comment by bajtos** [comment]
I discovered the issue while investigating https://github.com/filecoin-station/spark-evaluate/issues/312 and https://github.com/filecoin-station/core/issues/569

**Comment by juliangruber** [comment]
I don't know how this happened, but fixed by redeploying accordingly to https://github.com/filecoin-station/spark-api/tree/main/logshipper

```
fly deploy --file-local="/etc/vector/vector.toml=vector.toml"
```
